version: "3.7"

services: 
    ngnix-server:
        image: nginx:latest
        ports: 
            - "8080:80"
        volumes: 
            - './nginx.conf:/etc/ngnix/nginx.conf'
        networks: 
            - "test"
    ngnix-server1:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - './nginx1.conf:/etc/ngnix/nginx.conf'
        networks:
            - "test"
    mysql:
      container_name: mysql
      image: percona:8-centos
      volumes:
        - ./docker/mysql/setup:/docker-entrypoint-initdb.d
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/conf:/etc/mysql/conf.d:ro
      environment:
        - MYSQL_ROOT_PASSWORD=sc@dcsac@3
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
      stop_grace_period: 20s 
      restart: always
      networks:
          - "test"
  
networks: 
    test:
